services:
  example-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ms-example-usage
    ports:
      - "8080:8080"
    expose:
      - "8080"
    env_file:
      - .env
